build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - set CONAN_USERNAME=fogofogo
  - set CONAN_REFERENCE=opus/1.2.1
  - set CONAN_UPLOAD=https://api.bintray.com/conan/fogofogo/opus
  - set CONAN_REMOTES=https://api.bintray.com/conan/fogofogo/opus
  - set CONAN_STABLE_BRANCH_PATTERN=stable/.+
  - set CONAN_UPLOAD_ONLY_WHEN_STABLE=1
  - python build.py

